# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jiffy_test
      DATABASE_HOST: database

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      
      # Builds the image using the docker-compose.yml file
      - name: Build image
        run: docker-compose build

      - name: Show files
        run: ls -l

      - name: Run postgres
        run: docker-compose up -d database

      - name: Run redis
        run: docker-compose up -d redis

      - name: Check services
        run: docker-compose ps
        
      - name: Check ruby version
        run: ruby -v
        
      - name: Check container ruby version
        run: docker-compose run --rm web ruby -v
        
      - name: Install rake
        run: docker-compose run --rm web gem install rake && bundle install
        
      - name: Create development log
        run: touch /home/runner/work/jiffy/jiffy/log/development.log
        
      - name: Add permission to development log
        run: chmod 0666 /home/runner/work/jiffy/jiffy/log/development.log

      # Setup the database and run specs
      - name: Run specs
        run: docker-compose run --rm web bin/rails db:setup && bin/rails db:migrate && bundle exec rspec -fd
        
      - name: Stop services
        run: docker-compose down -v
