# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Maps tcp port 5432 on service container to the host
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jiffy_test
      DATABASE_HOST: localhost
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      
      - name: Show files
        run: ls -l
        
      - name: Check ruby version
        run: ruby -v
        
      - name: Install rake
        run: gem install rake && bundle install
        
      - name: Create development log
        run: touch /home/runner/work/jiffy/jiffy/log/development.log
        
      - name: Add permission to development log
        run: chmod 0666 /home/runner/work/jiffy/jiffy/log/development.log

      # Setup the database and run specs
      - name: Run specs
        run: bin/rails db:setup && bin/rails db:migrate && bundle exec rspec -fd
        
